"""Data models for Bedrock Cost Tracker invocation records."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from typing import Dict, Optional


@dataclass
class InvocationRecord:
    """Represents a single tracked Bedrock model invocation.

    Emitted to CloudWatch/S3 after each instrumented Bedrock API call.
    Contains token usage, cost estimate, and attribution metadata.
    """

    request_id: str
    """Bedrock request ID from the response headers."""

    model_id: str
    """Model identifier, e.g. 'anthropic.claude-3-sonnet-20240229-v1:0'."""

    input_tokens: int
    """Number of input tokens consumed by this invocation."""

    output_tokens: int
    """Number of output tokens generated by this invocation."""

    estimated_cost_usd: Optional[Decimal]
    """Estimated cost in USD based on pricing lookup. None if model pricing is unknown."""

    timestamp: datetime
    """UTC timestamp when the invocation occurred."""

    latency_ms: int
    """End-to-end call duration in milliseconds."""

    account_id: str
    """Source AWS account ID."""

    region: str
    """AWS region where the invocation was made."""

    tags: Dict[str, str] = field(default_factory=dict)
    """Cost allocation tags: team, application, environment, and custom tags."""

    inference_profile_arn: Optional[str] = None
    """Application Inference Profile ARN, if the call was routed through one."""

    stream: bool = False
    """Whether this was a streaming invocation."""

    stream_interrupted: bool = False
    """True if a streaming response was interrupted before completion."""

    api_method: str = "invoke_model"
    """API method used: 'invoke_model' | 'invoke_model_with_response_stream' | 'converse' | 'converse_stream'."""
